### ISSUE TITLE
Tidy Up grid.css

### ISSUE THREAD

**Issue by eync** [eync/superbro#1]
Starting from line 16 till 43 at [grid.css](https://github.com/eync/superbro/blob/master/css/grid.css) needs some tidying.

**Comment by wswapped** [comment]
On 16, can combining these styles into one make sense? It seems like one style repeated over several classes.

**Comment by eync** [comment]
Please go ahead and show your suggestion

**Comment by wswapped** [comment]
Alright, let me create a PR and demonstrate my suggestions

**Comment by eync** [comment]
Your suggestion might create new problems since it's taking everything that has word "span" in it. If someone would like to make class called "spanned" or "spank" or "dispan" it would include those css definitions too. It needs to be more specified I guess to work 👍

**Comment by wswapped** [comment]
Sure, How about we select only classes starting with `span` and ending in a number? maybe that can be more specific or we change names to something like `span-1` which can fix the problem

**Comment by eync** [comment]
How would that 1st option work? Could you demonstrate? :)
The second option is the last chance we might have but it will break the current sites if they update :P that's only problem. At least they have to change all the span classes to span- .
