### ISSUE TITLE
Buttons make other content to "jump" / "pop" slightly when hovered

### ISSUE THREAD

**Issue by eync** [eync/superbro#2]
[The Problem (mp4)](https://i.gyazo.com/ddbc4ff444e1c1220092c3b35ba1b9a4.mp4)
Tested on chrome Version 85.0.4183.121 (64-bit) and firefox developer edition Version 82.0b2 (64-bit).
Might be something to do with [.button @ settings.css : line 160](https://github.com/eync/superbro/blob/master/css/settings.css#L160).  Or perhaps overlap between different display types.

**Comment by Utsav-Ladani** [comment]
hey @eync , I want to fix this bug. Can i go ahead?

**Comment by eync** [comment]
Please do

**Comment by Utsav-Ladani** [comment]
Please review and merge PR
Thanks :)

**Comment by eync** [comment]
hey awesome, you found it! Could you replace the removed line with `border-color: var(--a-button-hover-bdr);`, and then I will merge it! Looks like the border setting while hovered was the problem with size of 1px. 

🥇

**Comment by Utsav-Ladani** [comment]
Issue #2
Hey @eync , I add this line in code.
Check and merge PR.
Happy Hecktoberfest :)

**Comment by Utsav-Ladani** [comment]
Thanks :+1:
